Repository MSB-s-Projects/Git-scm-Clone, pull requests merged in 2023-02, with the labels that each got.

#6 Added script and randomized tagline of the page
  index.html
  index.js
Labels: enhancement, pwoc, medium

#10 Create downloads page
  css/styles.css
  images/nav-download-gui.png
  images/nav-get-involved.png
  images/nav-read-book.png
  index.html
  pages/download.html
Labels: enhancement, help wanted, pwoc, hard

#11 Fixes issue #8
  index.html
Labels: bug, easy, pwoc
